---
- name: config Filebeat.yml
  hosts: router
  become: yes

  tasks:

  - name: Install config
    template:
      src: /var/lib/jenkins/tmp/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: 0600

  - name: Check config
    command: filebeat test config

  - name: Restart filebeat service
    service:
      name: filebeat
      state: restarted