---
- name: deploy node_exporter
  hosts: all_hosts
  become: yes

  tasks:

  - name: move node exporter to /usr/local/bin on host
    copy:
      src: /ansible/files/node_exporter-1.3.0.linux-amd64/node_exporter
      dest: /usr/local/bin/node_exporter
      owner: root
      group: root
      mode: 0755

  - name: Install service
    template:
      src: /var/lib/jenkins/tmp/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode: 0600
    register: node_serv

  - name: configure systemd to use service
    systemd:
      daemon_reload: yes
      name: node_exporter.service
      enabled: yes
      state: restarted      
    when: node_serv.changed


---
- hosts: all
  become: true

  tasks:

  - name: Install httpd service
    package:
      name: "httpd"
      state: "latest"

  - name: Start and enable httpd service
    service:
      name: "httpd"
      state: "started"
      enabled: "yes"

  - name: create a file with text
    copy:
      content: "Welcome to my web server"
      dest: /var/www/html/index.html
      force: no
      group: wheel
      owner: ruslan
      mode: 0644

  - name: Install httpd service
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: open port 443
    firewalld:
      service: https
      permanent: true
      state: enabled
